from __future__ import annotations

from nexova_ai.assistant.contracts import ToolSpec
from nexova_ai.assistant import tools


TOOL_REGISTRY: dict[str, ToolSpec] = {
    "sales_summary": ToolSpec(
        name="sales_summary",
        label="Sales Summary",
        description="Summarize submitted sales invoices.",
        category="accounts",
        required_doctypes=("Sales Invoice",),
        risk_level="medium",
        aliases=("sales", "today sales", "farokht", "فروخت"),
        handler=tools.sales_summary,
    ),
    "purchase_summary": ToolSpec(
        name="purchase_summary",
        label="Purchase Summary",
        description="Summarize submitted purchase invoices.",
        category="accounts",
        required_doctypes=("Purchase Invoice",),
        risk_level="medium",
        aliases=("purchase", "buying", "khareed", "خرید"),
        handler=tools.purchase_summary,
    ),
    "stock_balance": ToolSpec(
        name="stock_balance",
        label="Stock Balance",
        description="Summarize stock balance from Bin.",
        category="stock",
        required_doctypes=("Bin",),
        risk_level="medium",
        aliases=("stock", "inventory", "maal", "اسٹاک"),
        handler=tools.stock_balance,
    ),
    "receivables_summary": ToolSpec(
        name="receivables_summary",
        label="Receivables Summary",
        description="Summarize outstanding submitted sales invoices.",
        category="accounts",
        required_doctypes=("Sales Invoice",),
        risk_level="medium",
        aliases=("receivables", "outstanding", "unpaid", "وصول"),
        handler=tools.receivables_summary,
    ),
    "payables_summary": ToolSpec(
        name="payables_summary",
        label="Payables Summary",
        description="Summarize outstanding submitted purchase invoices.",
        category="accounts",
        required_doctypes=("Purchase Invoice",),
        risk_level="medium",
        aliases=("payables", "supplier due", "واجب الادا"),
        handler=tools.payables_summary,
    ),
    "customer_summary": ToolSpec(
        name="customer_summary",
        label="Customer Summary",
        description="Count readable customer records.",
        category="crm",
        required_doctypes=("Customer",),
        risk_level="low",
        aliases=("customer", "client", "گاہک"),
        handler=tools.customer_summary,
    ),
    "supplier_summary": ToolSpec(
        name="supplier_summary",
        label="Supplier Summary",
        description="Count readable supplier records.",
        category="buying",
        required_doctypes=("Supplier",),
        risk_level="low",
        aliases=("supplier", "vendor", "سپلائر"),
        handler=tools.supplier_summary,
    ),
    "item_lookup": ToolSpec(
        name="item_lookup",
        label="Item Lookup",
        description="Find readable matching items.",
        category="stock",
        required_doctypes=("Item",),
        risk_level="low",
        aliases=("item", "product", "sku", "آئٹم"),
        handler=tools.item_lookup,
    ),
    "quotation_summary": ToolSpec(
        name="quotation_summary",
        label="Quotation Summary",
        description="Count readable quotations.",
        category="selling",
        required_doctypes=("Quotation",),
        risk_level="low",
        aliases=("quotation", "quote", "کوٹیشن"),
        handler=tools.quotation_summary,
    ),
    "sales_order_summary": ToolSpec(
        name="sales_order_summary",
        label="Sales Order Summary",
        description="Count readable sales orders.",
        category="selling",
        required_doctypes=("Sales Order",),
        risk_level="low",
        aliases=("sales order", "sale order"),
        handler=tools.sales_order_summary,
    ),
    "purchase_order_summary": ToolSpec(
        name="purchase_order_summary",
        label="Purchase Order Summary",
        description="Count readable purchase orders.",
        category="buying",
        required_doctypes=("Purchase Order",),
        risk_level="low",
        aliases=("purchase order",),
        handler=tools.purchase_order_summary,
    ),
    "invoice_summary": ToolSpec(
        name="invoice_summary",
        label="Invoice Summary",
        description="Summarize readable sales or purchase invoices.",
        category="accounts",
        required_doctypes=("Sales Invoice",),
        risk_level="medium",
        aliases=("invoice", "bill", "انوائس"),
        handler=tools.invoice_summary,
    ),
    "profit_and_loss": ToolSpec(
        name="profit_and_loss",
        label="Profit and Loss",
        description="Estimate income, expenses, and net result from readable GL entries.",
        category="accounts",
        required_doctypes=("GL Entry", "Account"),
        risk_level="high",
        aliases=("profit and loss", "pnl", "nafa nuqsan"),
        handler=tools.profit_and_loss,
    ),
    "cash_bank_balance": ToolSpec(
        name="cash_bank_balance",
        label="Cash and Bank Balance",
        description="Summarize readable cash and bank account balances.",
        category="accounts",
        required_doctypes=("Account", "GL Entry"),
        risk_level="high",
        aliases=("cash balance", "bank balance", "cash bank"),
        handler=tools.cash_bank_balance,
    ),
    "account_balance": ToolSpec(
        name="account_balance",
        label="Account Balance",
        description="Show balance for an exact readable account.",
        category="accounts",
        required_doctypes=("Account", "GL Entry"),
        risk_level="high",
        aliases=("account balance", "ledger balance", "khata balance"),
        handler=tools.account_balance,
    ),
    "party_ledger": ToolSpec(
        name="party_ledger",
        label="Party Ledger",
        description="Open or prepare ledger-by-party navigation.",
        category="accounts",
        required_doctypes=("GL Entry",),
        risk_level="medium",
        aliases=("party ledger", "customer ledger", "supplier ledger"),
        handler=tools.party_ledger,
    ),
    "item_wise_sales": ToolSpec(
        name="item_wise_sales",
        label="Item-wise Sales",
        description="Summarize sales invoice item amounts by item.",
        category="selling",
        required_doctypes=("Sales Invoice Item",),
        risk_level="medium",
        aliases=("item wise sales", "product wise sales", "sales by item"),
        handler=tools.item_wise_sales,
    ),
    "customer_wise_sales": ToolSpec(
        name="customer_wise_sales",
        label="Customer-wise Sales",
        description="Summarize sales by customer.",
        category="selling",
        required_doctypes=("Sales Invoice",),
        risk_level="medium",
        aliases=("customer wise sales", "sales by customer"),
        handler=tools.customer_wise_sales,
    ),
    "low_stock": ToolSpec(
        name="low_stock",
        label="Low Stock",
        description="Show low or zero stock bins.",
        category="stock",
        required_doctypes=("Bin",),
        risk_level="medium",
        aliases=("low stock", "reorder", "stock kam"),
        handler=tools.low_stock,
    ),
    "slow_moving_items": ToolSpec(
        name="slow_moving_items",
        label="Slow Moving Items",
        description="Open stock movement analysis guidance.",
        category="stock",
        required_doctypes=("Stock Ledger Entry",),
        risk_level="medium",
        aliases=("slow moving", "dead stock"),
        handler=tools.slow_moving_items,
    ),
    "gross_profit": ToolSpec(
        name="gross_profit",
        label="Gross Profit",
        description="Open gross profit report guidance.",
        category="selling",
        required_doctypes=("Sales Invoice",),
        risk_level="high",
        aliases=("gross profit", "gross margin", "margin"),
        handler=tools.gross_profit,
    ),
    "expenses_summary": ToolSpec(
        name="expenses_summary",
        label="Expenses Summary",
        description="Summarize bounded readable expenses from GL entries.",
        category="accounts",
        required_doctypes=("GL Entry", "Account"),
        risk_level="high",
        aliases=("expenses", "expense", "kharcha"),
        handler=tools.expenses_summary,
    ),
    "payroll_summary": ToolSpec(
        name="payroll_summary",
        label="Payroll Summary",
        description="Count readable payroll records.",
        category="hr",
        required_doctypes=("Salary Slip",),
        risk_level="high",
        aliases=("payroll", "salary", "tankhwa"),
        handler=tools.payroll_summary,
    ),
    "attendance_summary": ToolSpec(
        name="attendance_summary",
        label="Attendance Summary",
        description="Count readable attendance records.",
        category="hr",
        required_doctypes=("Attendance",),
        risk_level="medium",
        aliases=("attendance", "hazri"),
        handler=tools.attendance_summary,
    ),
    "manufacturing_summary": ToolSpec(
        name="manufacturing_summary",
        label="Manufacturing Summary",
        description="Count readable manufacturing work orders.",
        category="manufacturing",
        required_doctypes=("Work Order",),
        risk_level="medium",
        aliases=("manufacturing", "production", "work order"),
        handler=tools.manufacturing_summary,
    ),
    "crm_summary": ToolSpec(
        name="crm_summary",
        label="CRM Summary",
        description="Count readable leads and opportunities.",
        category="crm",
        required_doctypes=("Lead", "Opportunity"),
        risk_level="medium",
        aliases=("lead", "opportunity", "crm"),
        handler=tools.crm_summary,
    ),
    "project_summary": ToolSpec(
        name="project_summary",
        label="Project Summary",
        description="Count readable projects.",
        category="projects",
        required_doctypes=("Project",),
        risk_level="medium",
        aliases=("project", "task"),
        handler=tools.project_summary,
    ),
    "asset_summary": ToolSpec(
        name="asset_summary",
        label="Asset Summary",
        description="Count readable assets.",
        category="assets",
        required_doctypes=("Asset",),
        risk_level="medium",
        aliases=("asset", "fixed asset"),
        handler=tools.asset_summary,
    ),
    "tax_summary": ToolSpec(
        name="tax_summary",
        label="Tax Summary",
        description="Open tax report guidance.",
        category="accounts",
        required_doctypes=("Sales Invoice",),
        risk_level="high",
        aliases=("tax", "gst", "sales tax"),
        handler=tools.tax_summary,
    ),
    "trend_analysis": ToolSpec(
        name="trend_analysis",
        label="Trend Analysis",
        description="Clarify trend, comparison, and forecast questions.",
        category="analytics",
        required_doctypes=(),
        risk_level="medium",
        aliases=("trend", "compare", "forecast"),
        handler=tools.trend_analysis,
    ),
}


def get_tool(intent: str) -> ToolSpec | None:
    return TOOL_REGISTRY.get(intent)
