from __future__ import annotations

from nexova_ai.assistant.contracts import ToolSpec
from nexova_ai.assistant import tools


TOOL_REGISTRY: dict[str, ToolSpec] = {
    "sales_summary": ToolSpec(
        name="sales_summary",
        label="Sales Summary",
        description="Summarize submitted sales invoices.",
        category="accounts",
        required_doctypes=("Sales Invoice",),
        risk_level="medium",
        aliases=("sales", "today sales", "farokht", "فروخت"),
        handler=tools.sales_summary,
    ),
    "purchase_summary": ToolSpec(
        name="purchase_summary",
        label="Purchase Summary",
        description="Summarize submitted purchase invoices.",
        category="accounts",
        required_doctypes=("Purchase Invoice",),
        risk_level="medium",
        aliases=("purchase", "buying", "khareed", "خرید"),
        handler=tools.purchase_summary,
    ),
    "stock_balance": ToolSpec(
        name="stock_balance",
        label="Stock Balance",
        description="Summarize stock balance from Bin.",
        category="stock",
        required_doctypes=("Bin",),
        risk_level="medium",
        aliases=("stock", "inventory", "maal", "اسٹاک"),
        handler=tools.stock_balance,
    ),
    "receivables_summary": ToolSpec(
        name="receivables_summary",
        label="Receivables Summary",
        description="Summarize outstanding submitted sales invoices.",
        category="accounts",
        required_doctypes=("Sales Invoice",),
        risk_level="medium",
        aliases=("receivables", "outstanding", "unpaid", "وصول"),
        handler=tools.receivables_summary,
    ),
    "payables_summary": ToolSpec(
        name="payables_summary",
        label="Payables Summary",
        description="Summarize outstanding submitted purchase invoices.",
        category="accounts",
        required_doctypes=("Purchase Invoice",),
        risk_level="medium",
        aliases=("payables", "supplier due", "واجب الادا"),
        handler=tools.payables_summary,
    ),
    "customer_summary": ToolSpec(
        name="customer_summary",
        label="Customer Summary",
        description="Count readable customer records.",
        category="crm",
        required_doctypes=("Customer",),
        risk_level="low",
        aliases=("customer", "client", "گاہک"),
        handler=tools.customer_summary,
    ),
    "supplier_summary": ToolSpec(
        name="supplier_summary",
        label="Supplier Summary",
        description="Count readable supplier records.",
        category="buying",
        required_doctypes=("Supplier",),
        risk_level="low",
        aliases=("supplier", "vendor", "سپلائر"),
        handler=tools.supplier_summary,
    ),
    "item_lookup": ToolSpec(
        name="item_lookup",
        label="Item Lookup",
        description="Find readable matching items.",
        category="stock",
        required_doctypes=("Item",),
        risk_level="low",
        aliases=("item", "product", "sku", "آئٹم"),
        handler=tools.item_lookup,
    ),
    "quotation_summary": ToolSpec(
        name="quotation_summary",
        label="Quotation Summary",
        description="Count readable quotations.",
        category="selling",
        required_doctypes=("Quotation",),
        risk_level="low",
        aliases=("quotation", "quote", "کوٹیشن"),
        handler=tools.quotation_summary,
    ),
    "sales_order_summary": ToolSpec(
        name="sales_order_summary",
        label="Sales Order Summary",
        description="Count readable sales orders.",
        category="selling",
        required_doctypes=("Sales Order",),
        risk_level="low",
        aliases=("sales order", "sale order"),
        handler=tools.sales_order_summary,
    ),
    "purchase_order_summary": ToolSpec(
        name="purchase_order_summary",
        label="Purchase Order Summary",
        description="Count readable purchase orders.",
        category="buying",
        required_doctypes=("Purchase Order",),
        risk_level="low",
        aliases=("purchase order",),
        handler=tools.purchase_order_summary,
    ),
    "invoice_summary": ToolSpec(
        name="invoice_summary",
        label="Invoice Summary",
        description="Summarize readable sales or purchase invoices.",
        category="accounts",
        required_doctypes=("Sales Invoice",),
        risk_level="medium",
        aliases=("invoice", "bill", "انوائس"),
        handler=tools.invoice_summary,
    ),
}


def get_tool(intent: str) -> ToolSpec | None:
    return TOOL_REGISTRY.get(intent)
